feat: fix footer
SolidPracticum/Toiber pull request #14
Opened 2022-11-19 11:42 UTC by Turdubaevajazgul

Issue #:
[Notion](https://www.notion.so/80ce8a70757c459a8ddf4333d3e0d43f?v=bd2c354608e249efa31cb5d6e2330cc1)

## PR type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Screenshots

#### before:

#### after:

## Does this introduce a breaking change?

- [ ] Yes (please describe):
- [ ] No

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Accessibility support has been tested
- [ ] Responsive layout and functionality have been tested
  - [ ] desktop and mobile view responsiveness are supported
  - [ ] no loss of functionality or content when zoomed in to 400%
  - [ ] no horizontal scrolling when zoomed in to 400% (only vertical scrolling, exception: DataGrids)
- [ ] avoids using many levels of prop drilling
- [ ] check console on errors and warnings.
---

References:
- [Clean code](https://github.com/airbnb/javascript)

2022-11-20 18:50 UTC, Improove3567 commented on src/App.js
> +// import { PrivateRoute, PublicRoute } from "./routes/routes";
уберите комменты

2022-11-20 18:52 UTC, Improove3567 commented on src/components/footer/Footer.module.scss
> +    height: 500px;
height в px не задаем

2022-11-20 18:53 UTC, Improove3567 commented on src/components/footer/Footer.module.scss
> +            bottom: -120px;
и это тоже исправьте

2022-11-20 18:53 UTC, Improove3567 commented on src/components/footer/Footer.module.scss
> +        bottom: -110px;
и это

2022-11-20 18:53 UTC, Improove3567 commented on src/components/footer/Footer.module.scss
> +        height: 550px;
не задаем в px

2022-11-20 18:53 UTC, Improove3567 commented on src/components/footer/Footer.module.scss
> +        height: 800px;
тут тоже

2022-11-20 18:53 UTC, Improove3567 commented on src/components/footer/Footer.module.scss
> +        height: 800px;
и тут

2022-11-20 18:53 UTC, Improove3567 commented on src/components/footer/Footer.module.scss
> +        height: 800px;
и тут

2022-11-20 18:54 UTC, Improove3567 commented on src/components/footer/Footer.module.scss
> +        height: 800px;
и тут

2022-11-20 18:54 UTC, Improove3567 commented on src/components/footer/Footer.module.scss
> +        height:820px;
тут тоже

2022-11-22 13:15 UTC, asylbekovkairat commented
неправильное название ветки, сегодня на созвоне обсудим

2022-11-22 13:17 UTC, asylbekovkairat commented on src/components/footer/Footer.module.scss
> +    .Wrapper {
с маленькой буквы пишем селекторы

2022-11-22 13:17 UTC, asylbekovkairat reviewed
решаем комменты и обратно на ревью

2022-11-23 15:08 UTC, asylbekovkairat commented on src/components/footer/Footer.jsx
> +                <img className={css.image} src="./images/footer/instagram.svg" alt="instagram" />
нужно мапить картинки

2022-11-23 16:39 UTC, Turdubaevajazgul commented on src/components/footer/Footer.module.scss
> -    .ServiceLink {
Нет верстка не сломалась. Все работает

2022-11-24 11:23 UTC, Bezymeys requested changes

2022-11-24 11:23 UTC, Bezymeys commented on src/components/footer/Footer.jsx
> +                  <img className={css.image} src={items.img} alt="logo" />
обернуть ссылкой

2022-11-24 11:23 UTC, Bezymeys commented on src/components/footer/Footer.jsx
> +                <img className={css.logoImg} src="./images/footer/logo.svg" alt="logo" />
same

2022-11-24 11:23 UTC, Bezymeys commented on src/components/footer/Footer.jsx
>                    <Link to="#" key={items.id}>
add style for link(hover)

2022-11-24 11:23 UTC, Bezymeys commented on src/components/footer/Footer.jsx
> +              <p>@{t("footer.Reserv")}</p>
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/100524271/203771856-0bbac30e-aa77-4454-bf83-161e07a93c9d.png">
edit height

2022-11-30 13:25 UTC, asylbekovkairat commented on src/App.scss
> +@mixin font_style {
миксины должны быть в отдельной файле

2022-11-30 13:25 UTC, asylbekovkairat commented on src/components/footer/Footer.jsx
> +                <Link to="#">
роуты для Link

2022-11-30 13:26 UTC, asylbekovkairat commented on src/components/footer/Footer.jsx
> +              <div className={css.social}>
пишем не css, а scss или styles

2022-11-30 14:17 UTC, Adilxa commented on src/App.scss
> +a {
Дайте лучше шрифт всем элементам через *

2022-11-30 14:41 UTC, Improove3567 commented on src/App.scss
> +  font-family: "Montserrat", sans-serif !important;
уберите здесь шрифт, так как вы его уже поставили в index.scss

2022-11-30 14:42 UTC, Improove3567 commented on src/components/footer/Footer.jsx
>                    <Link to="#" key={items.id}>
дайте ему ссылку, вместо #

2022-11-30 14:42 UTC, Improove3567 commented on src/components/footer/Footer.jsx
> +                <Link to="/link">
"/link" такой путь не пойдет

2022-11-30 14:43 UTC, Improove3567 commented on src/components/footer/Footer.jsx
> +                  <Link to="#" key={items.id}>
здесь тоже дайте путь

2022-12-01 14:16 UTC, Improove3567 commented on src/constants/FooterLinks.jsx
> +    puth: "/Map",
сделайте везде с маленькой буквы

2022-12-05 06:19 UTC, asylbekovkairat commented
не нужно добавлять скрины кода в PR template

2022-12-05 06:21 UTC, asylbekovkairat commented on public/shared/locales/ru/translation.json
> +        "Info":"Этот сайт является полностью коммерческим и не содержит провакационной и иной информации противоречащий законам",
провокационный*

2022-12-05 06:21 UTC, asylbekovkairat commented on public/shared/locales/ru/translation.json
> +        "Info":"Этот сайт является полностью коммерческим и не содержит провакационной и иной информации противоречащий законам",
почему файл с переводами у вас стоит не правильно, нужно так как настраивал Азим

2022-12-05 06:22 UTC, asylbekovkairat commented on src/App.scss
> -  font-family: "Montserrat", sans-serif !important;
ну задайте вы этот font-familу глобально в папке app.css

2022-12-05 06:22 UTC, asylbekovkairat commented on src/components/footer/Footer.jsx
> +                  <Link to={items.puth} key={items.id}>
если вы в to имели ввиду путь то нужно написать path

2022-12-07 14:00 UTC, Improove3567 commented on src/App.js
> +        <Route path="/logo" element={<PublicRoute Component={Footer} />} />
почему path="logo" ?

2022-12-07 16:11 UTC, asylbekovkairat approved these changes

2022-12-07 17:04 UTC, merged